config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  authenticate do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :others

  resources :rheumatologists

  get 'home/index'

  resources :users do

    member do
      get :network
      post :nation
    end

    collection do
      get :admin
      get :census
    end

    resources :physicians

    resources :paths

    resources :rads

  end

  devise_for :members, controllers: {registrations: 'members/registrations',
                                     sessions: 'members/sessions' }

  devise_scope :member do
    authenticated :member do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :member do
      root :to => 'members/registrations#new', as: :unauthenticated_root
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user.nonild.nil? ? nonild = 0 : nonild = @user.nonild
    @user.ipfpatients.nil? ? ipfpatients = 0 : ipfpatients = @user.ipfpatients
    @user.sarcoidpatients.nil? ? sarcoidpatients = 0 : sarcoidpatients = @user.nonild
    @user.iippatients.nil? ? iippatients = 0 : iippatients = @user.iippatients
    @user.ctdpatients.nil? ? ctdpatients = 0 : ctdpatients = @user.ctdpatients
    @user.unclasspatients.nil? ? unclasspatients = 0 : unclasspatients = @user.unclasspatients
    @user.hppatients.nil? ? hppatients = 0 : hppatients = @user.hppatients
    @user.other.nil? ? other = 0 : other = @user.other

    @cases = [['Non-ILD', nonild],
              ['IPF', ipfpatients],
              ['Sarcoidosis', sarcoidpatients],
              ['Non-IPF IIP', iippatients],
              ['CTDs', ctdpatients],
              ['Unclassifiable', unclasspatients],
              ['Hypersensitivity pneumonitis', hppatients],
              ['Other', other]]

    @cases = @cases.reject {|a| a[1] == 0 }
    @participants_notifier = true if @user.rads.blank? && @user.physicians.blank? && @user.paths.blank? && @user.rheumatologists.blank? && @user.others.blank?
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:error] =  @user.errors.full_messages.to_sentence
        format.html { redirect_to edit_user_path(@user)}
        format.js { render :nothing => true}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    completion = @user.user_complete
    respond_to do |format|
      if @user.update(user_params)
        # CompletedWorker.perform_async(@user.member.email) unless completion == true
        CompletionMailer.notify_admin_completion(@user.member.email).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:error] =  @user.errors.full_messages
        format.html { render :edit }
        format.json { }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def network
    @user_country_array = Array.new
    @user_country_array = User.all.map {|user| user.country }.reject{ |country| country.nil? }.uniq.sort
    @user_count = User.all.select { |u| u.user_complete == true }.count
    @user_json = User.all.group_by(&:iso).map{|k,v| [k, v.count, k.to_s.downcase]}.map {|c, v | ["code" => c, "value" => v, "flag" => c.to_s.downcase]}.flatten.to_json
    @sectiona =  User.all.group('practice').count.map { |k,v| [ "name" => k, "y" => v] unless k.nil?}.reject { |a| a.blank? }.flatten.to_json
    render 'network'
  end

  def nation
    @iso = get_iso params[:user][:nation]
    @nation = params[:user][:nation]
    @user_country_array = Array.new
    @user_count_country = User.select { |u| u.user_complete == true && u.country == @nation }.count
    @nation_practices =  User.where(country: @nation).group('practice').count.map { |k,v| [ "name" => k, "y" => v] unless k.nil?}.reject { |a| a.blank? }.flatten.to_json
    @nation_institutions =  User.where(country: @nation).group('institute_type').count.map { |k,v| [ "name" => k, "y" => v] unless k.nil?}.reject { |a| a.blank? }.flatten.to_json
    @nation_biopsy =
            User.where(country: @nation)
            .group(:institute_type)
            .select(:institute_type, "AVG(biopsy) AS biopsy_count")
            .flat_map { |group| ["name" => group.institute_type, "y" => group.biopsy_count.ceil]}.to_json

    # Get rads
    @arr_rads = Array.new
    @test = User.all.map{ |u| u if u.country == @nation }.reject {|u| u.nil?}.each do |u|
      u.rads ? @arr_rads << u.rads.count : 0
    end
    # Get physicians
    @arr_phys = Array.new
    @test = User.all.map{ |u| u if u.country == @nation }.reject {|u| u.nil?}.each do |u|
      u.physicians.any? ? @arr_phys << u.physicians.count : 0
    end
    # Get pathologists
    @arr_paths = Array.new
    @test = User.all.map{ |u| u if u.country == @nation }.reject {|u| u.nil?}.each do |u|
      u.paths.any? ? @arr_paths << u.paths.count : 0
    end
    # Get rheumatologists
    @arr_rheum = Array.new
    @test = User.all.map{ |u| u if u.country == @nation }.reject {|u| u.nil?}.each do |u|
      u.rheumatologists.any? ? @arr_rheum << u.rheumatologists.count : 0
    end
    render 'country'
  end

  def admin
    @visits = Visit.all.order(:created_at => :desc).paginate(page: params[:page], :per_page => 50)
    if current_user.admin?
      render 'users/admin/raw'
    else
      sign_out_and_redirect(current_member)
    end
  end

  def census
    if current_user.admin?
      @users = User.all
      @user_count = User.all.select { |u| u.user_complete == true }.count
      render 'users/admin/census'
    else
      sign_out_and_redirect(current_member)
    end
  end

  private

    def check_complete
      unless current_user.attributes.select { |a, v| v == nil }.reject { |a, v|  a == "radiologist" || a == "pathologist"}.empty?
        flash[:error] =  "Please complete the form details before proceeding"
        redirect_to edit_user_path(current_user)
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:experience,
                                   :kind,
                                   :practice,
                                   :biopsy,
                                   :cryobiopsy,
                                   :nonild,
                                   :specialist,
                                   :skip,
                                   :ipfpatients,
                                   :hppatients,
                                   :sarcoidpatients,
                                   :iippatients,
                                   :ctdpatients,
                                   :unclasspatients,
                                   :other,
                                   :country,
                                   :institute,
                                   :ipf,
                                   :institute_type,
                                   :schedule,
                                   :cases,
                                   :document,
                                   :nation,
                                   :imaging,
                                   :histopathology,
                                   :teleconference,
                                   :teleimaging,
                                   :telepath,
                                   rads_attributes: [:user_id, :experience, :kind, :id, :_destroy],
                                   paths_attributes: [:user_id, :experience, :kind, :id, :_destroy],
                                   rheumatologists_attributes: [:user_id, :experience, :kind, :id, :_destroy],
                                   others_attributes: [:user_id, :experience, :kind, :id, :_destroy],
                                   physicians_attributes: [:user_id, :experience, :kind, :id, :_destroy])
    end

end

app/views/users/_form.html.erb
<div class="row content">

  <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">


    <%=
        flash_messages @user
    %>


    <%= simple_form_for(@user, html: { :class => 'form-horizontal'} ) do |f| %>

        <div class="page-header">
          <h2>Interstitial lung disease evaluation</h2>
        </div>



<!--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

    <div class = "row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="page-header">
              <h3>A. How do you approach suspected cases of IPF?<br/></h3>
            </div>
        </div>
      <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">
          <div class="field">
          <%= f.collection_radio_buttons :practice, [[1, 'I make the diagnosis myself with the aid of diagnostic guidelines'],
                                                 [2, 'I make the diagnosis via a face-to-face MDT discussion'],
                                                 [3, 'If IPF is being considered I/we refer to an expert/academic ILD centre']],
                                         :first,
                                         :last,
                                         :item_wrapper_class => 'RadioBlock'%>
          </div>
        </div>
    </div>



<!--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

        <div class = "row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-header">
                  <h3>B. Your details <br/><small> Please answer all questions. Please also note that the option "Academic institution" is for <b>academic-only centres</b> (i.e. centres not directly linked to a hospital). If you work in a university hospital
                  select <b>"University hospital"</b></small></h3>
                </div>
            </div>

            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">

              <div class="field">
                <%= f.input :kind, collection: [ "Academic/Researcher", "Pulmonologist (fellowship trained)", "General physician with an interest in pulmonology", "General physician",
                                                 "Thoracic radiologist (fellowship trained)", "General radiologist with an interest in thoracic imaging", "General radiologist",
                                                 "Pulmonary pathologist (fellowship trained)", "General pathologist with an interest in pulmonary pathology", "General pathologist"] , label: "Which best describes your position?", class: 'form-control' %>
              </div><br/>

              <div class="field">
                <%= f.input :experience, collection: 1..50, label: "How many years experience do you have in this role?", class: 'form-control' %>
              </div><br/>

              <div class="field">
                <%= f.input :institute, label: "What is the name of your institution?", class: 'form-control' %>
              </div><br/>

                <div class="field">
                  <%= f.input :institute_type, collection: ["Academic institution", "University hospital", "Non-university hospital" ] , label: "What type of institution is this?", class: 'form-control'%>
                </div><br/>

                <div class="field">
                  <%= f.input :country, as: :country, label: "Which country is this institution in?" %>
                </div>

            </div>
        </div>

<!--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
        <div class = "row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="page-header">
              <h3>C. MDT activity<br/><small> Please answer all questions.</small></h3>
            </div>
          </div>


        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 ">


            <div class="field">
              <%= f.input :specialist, collection: ["ILD dedicated MDT meeting", "General respiratory MDT meeting", "We don't have a formal respiratory MDT meeting"] , label: "Which best describes your MDT meeting?", class: 'form-control'%>
            </div><br/>

            <div class="field">
              <%= f.input :imaging, collection: ["Yes", "Not directly, but in my network", "No"] , label: "Do you have access to expert ILD radiology input?", class: 'form-control'%>
            </div><br/>

            <div class="field">
              <%= f.input :histopathology, collection: ["Yes", "Not directly, but in my network", "No"] , label: "Do you have access to expert ILD histopathology input?", class: 'form-control'%>
            </div><br/>

            <div class="field">
              <%= f.input :teleimaging, collection: ["Yes", "No"] , label: "Do you ever use teleconferencing to get an expert RADIOLOGIST'S opinion?", class: 'form-control'%>
            </div><br/>

            <div class="field">
              <%= f.input :telepath, collection: ["Yes", "No"] , label: "Do you ever use teleconferencing to get an expert PATHOLOGIST'S opinion?", class: 'form-control'%>
            </div><br/>


          </div>
        </div>


  <!--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

        <div class = "row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="page-header">
                  <h3>D. Other MDT participants<br/><small> Please answer all questions. To add a member, click on relevant specialty and add details in the created fields. <b>"Add new participant"</b> is for
                  adding a specialty that's not listed e.g. a geneticist, or ILD nurse. Please give details of this participant in the free text field created when
                    you press <b>"Add new participant"</b></small></h3>
                </div>
            </div>


        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 ">

                  <%= f.simple_fields_for :physicians do |physician| %>
                      <%= render 'physician_fields', f: physician %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add physician', f, :physicians, class: "btn btn-primary Component" %>
                  </div>

                  <%= f.simple_fields_for :rads do |rad| %>
                      <%= render 'rad_fields', f: rad %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add radiologist', f, :rads, class: "btn btn-info Component" %>
                  </div>

                  <%= f.simple_fields_for :paths do |path| %>
                      <%= render 'path_fields', f: path %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add pathologist', f, :paths, class: "btn btn-success Component" %>
                  </div>

                  <%= f.simple_fields_for :rheumatologists do |rheumatologist| %>
                      <%= render 'rheumatologist_fields', f: rheumatologist %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add rheumatologist', f, :rheumatologists, class: "btn btn-primary Component" %>
                  </div>

                  <%= f.simple_fields_for :others do |other| %>
                      <%= render 'other_fields', f: other %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add new participant', f, :others, class: "btn btn-info Component" %>
                  </div>


            </div>
        </div>

<!--/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
        <div class = "row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
           <div class="page-header">
            <h3>E. MDT case mix<br/><small> Please answer all questions. Note that there are no default values. If your
            answer is "0" then you must explictly select "0". This is to ensure all questions are considered. "%" means an estimate of
            the proportion of cases seen by your MDT (or you, if you do not have a dedicated MDT) with each diagnosis. </small></h3>
           </div>
          </div>

          <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">
            <div class = "CaseMixInputs">
                  <div class="field">
                    <%= f.input :schedule, collection: [ "Sporadically", "Daily", "Weekly", "Fortnightly", "Monthly", "Every 2 months", "Every 3 months", "Less frequently than every 3 months"] , label: "Frequency of MDT meeting", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :cases, collection:[ "0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100", ">100"] , label: "Number of new cases of ILD per month (approx)", class: 'form-control' %>
                  </div>
                 <div class="field">
                    <%= f.input :ipf, collection: [ "0-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100", ">100"] , label: "Number of new cases of IPF per month (approx)", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :biopsy, collection: 0..100, label: "Percentage of all ILD cases biopsied (approx)", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :cryobiopsy, collection: ["Yes", "No"], label: "Availability of cryobiopsy", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :document, collection: ["Yes", "No"], label: "Do you routinely record MDT outcome?", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :nonild, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Non-ILD", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :ipfpatients, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%IPF", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :hppatients, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Hypersensitivity pneumonitis", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :sarcoidpatients, collection: [0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Sarcoidosis", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :iippatients, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Non-IPF IIP", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :ctdpatients, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Connective tissue disease related ILD", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :unclasspatients, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Unclassifiable ILD", class: 'form-control' %>
                  </div>
                  <div class="field">
                    <%= f.input :other, collection: [ 0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100], label: "%Other (select 0 if none)", class: 'form-control' %>
                  </div>

                <div class="field">
                  <%= f.input :skip, as: :boolean, label: "I can't approximate %diagnoses", class: 'form-control'%>
                </div>


                  <div class="field">
                    <%= f.submit "Submit your data", class: "btn btn-primary SubmitData" %></h3>
                  </div>
            </div>
          </div>
        </div>


    <% end %>
  </div>
</div>

app/views/users/_path_fields.html.erb
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 ">
  <div class="nested-fields">
  <div class="page-header">
    <h3>Pathologist</h3>
  </div>
  <%= f.input :experience, collection: 1..50, label: "Pathologist experience (years)", class: 'form-control' %>
  <%= f.input :kind, collection: [ "Pulmonary pathologist (fellowship trained)", "General pathologist with an interest in pulmonary pathology", "General pathologist"] , label: "Type", class: 'form-control' %>
  <%= link_to_remove_association "Remove pathologist", f,  class: "btn btn-danger btn-xs Component" %>
</div>
</div>

app/views/users/_physician_fields.html.erb
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 ">
<div class="nested-fields">
  <div class="page-header">
    <h3>Physician</h3>
  </div>
  <%= f.input :experience, collection: 1..50, label: "Physician experience (years)", class: 'form-control' %>
  <%= f.input :kind, collection: [ "Pulmonologist (fellowship trained)", "General physician with an interest in pulmonology", "General physician"] , label: "Type", class: 'form-control' %>
  <%= link_to_remove_association "Remove physician", f,  class: "btn btn-danger btn-xs Component" %>
</div>
</div>

app/views/users/_rheumatologist_fields.html.erb
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 ">
  <div class="nested-fields">
  <div class="page-header">
    <h3>Rheumatologist</h3>
  </div>
  <%= f.input :experience, collection: 1..50, label: "Rheumatologist experience (years)", class: 'form-control' %>
  <%= f.input :kind, collection: [ "Rheumatologist with an interest in intersitial lung disease", "General rheumatologist"] , label: "Type", class: 'form-control' %>
  <%= link_to_remove_association "Remove rheumatologist", f,  class: "btn btn-danger btn-xs Component" %>
</div>
</div>

app/views/users/back_buttons_for_network_page.html.erb
<div class = "col-lg-6 col-lg-offset-3 col-md-6col-md-offset-3 col-sm-12 col-xs-12">
  <div class = "UserInputs">
    <div class = "Label">MDT frequency</div>
    <%= simple_form_for(@user, :url =>  freq_users_path, :method => :post, html: { class: "form-inline"} ) do |f| %>
        <%= f.input :country, as: :country, label: false,  class: "form-control"%>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

    <div class = "Label">New ILD cases per month</div>
    <%= simple_form_for(@user, :url =>  ild_users_path, :method => :post, html: { class: "form-inline"} ) do |f| %>
        <%= f.input :country, as: :country, label: false,  class: "form-control"%>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

    <div class = "Label">New cases of IPF per month</div>
    <%= simple_form_for(@user, :url =>  ipf_users_path, :method => :post, html: { class: "form-inline"} ) do |f| %>
        <%= f.input :country, as: :country, label: false,  class: "form-control"%>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">

    <%= render 'form' %>


</div>

app/views/users/freq.html.erb
<% if @frequency_test.blank? %>
        <div class="page-header">
          <h3>There is no data for this country yet</h3>
        </div>
    <%  else %>
        <div class = "MapContainer">
          <div id="container"></div>
        </div>


        <script>


            $(document).ready(function () {

                var data = <%=raw @frequency %>

                        $('#container').highcharts({
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: 'Multidisciplinary team meeting frequency'
                            },
                            subtitle: {
                                text: ''
                            },
                            xAxis: {
                                type: 'category'
                            },
                            yAxis: {
                                title: {
                                    text: 'Number of MDTs'
                                }

                            },
                            credits: {
                                enabled: false
                            },
                            legend: {
                                enabled: false
                            },
                            exporting: {
                                enabled: false
                            },
                            plotOptions: {
                                series: {
                                    pointPadding: 0.25,
                                    groupPadding: 0.25,
                                    borderWidth: 0,
                                    dataLabels: {
                                        enabled: true,
                                        format: '{point.y:f}'
                                    }
                                }
                            },

                            tooltip: {
                                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:f}</b>'
                            },

                            series: [{
                                name: "Number",
                                colorByPoint: true,
                                data: data
                            }]
                        })
            });


        </script>

    <% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Specialist</th>
      <th>Experience</th>
      <th>Institute</th>
      <th>Radiologist</th>
      <th>Pathologist</th>
      <th>Schedule</th>
      <th>Cases</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.specialist %></td>
        <td><%= user.experience %></td>
        <td><%= user.institute %></td>
        <td><%= user.radiologist %></td>
        <td><%= user.pathologist %></td>
        <td><%= user.schedule %></td>
        <td><%= user.cases %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/network.html.erb
<div class="row">
  <div class = "col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">

    <div class = "UserTally">
      <h4>Member count:<%= @user_count %></h4>
    </div>

    <div class = "MapContainer">
      <div id="container-maps"></div>
    </div>

    <div class = "col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
      <%= simple_form_for(current_user, :url =>  nation_user_path(current_user), :method => :post) do |f| %>
            <%= f.input :nation, collection: @user_country_array, label: "Select a country to view data on (only countries represented are listed)", class: 'form-control' %>
            <%= f.submit "Submit", class: "btn btn-primary" %></h3>
      <% end %>
    </div>




  </div>
</div>


<script>

    $(document).ready(function () {

        var data =  <%= raw @user_json %>



              // Initiate the chart
              $('#container-maps').highcharts('Map', {

                title : {
                  useHTML: true,
                  text : '<div style = "margin-bottom:40px; font-size: 0.8em;">Members by country (double click to zoom)</div>'
                },

                mapNavigation: {
                  enabled: true,
                  enableDoubleClickZoomTo: true
                },

                credits: {
                  enabled: false
                },

                exporting: {
                  enabled: false
                },

                legend: {
                  enabled: false
                },



                colorAxis: {
                  min: 1,
                  max: 1000,
                  type: 'logarithmic'
                },

                series : [{
                  data : data,
                  mapData: Highcharts.maps['custom/world'],
                  joinBy: ['iso-a2', 'code'],
                  name: 'Number of members',
                  states: {
                    hover: {
                      color: '#BADA55'
                    }
                  },
                  tooltip: {
                    valueSuffix: ''
                  }
                }]
              });


    });




</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>