config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  authenticate do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :others

  resources :rheumatologists

  get 'home/index'

  resources :users do

    member do
      get :network
      post :nation
    end

    collection do
      get :admin
      get :census
    end

    resources :physicians

    resources :paths

    resources :rads

  end

  devise_for :members, controllers: {registrations: 'members/registrations',
                                     sessions: 'members/sessions' }

  devise_scope :member do
    authenticated :member do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :member do
      root :to => 'members/registrations#new', as: :unauthenticated_root
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <span class = "name">
    The Global ILD Project
    </span>
  <nav>
    <ul>
      <%=
          # link_to "About"
      %>
      <%=
          # link_to "Contact"
      %>
      <li>
        <a href="https://uk.linkedin.com/in/SLFWalsh">SLFW</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class = "NavBarRestraint">
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand Logo" href="#">The Global ILD Project</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if member_signed_in? %>
              <% if current_user.admin == "true" && current_user.member.email == "slfwalsh@gmail.com" %>
                  <li class="Admin">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%=link_to "IP data", admin_users_path %></li>
                      <li><%=link_to "Email data", census_users_path %></li>
                    </ul>
                  </li>
              <% end %>
              <% if current_user.user_complete %>
                <li><%=link_to "View network", network_user_path(current_user) %></li>
                <li><%=link_to "My MDT", user_path(current_user) %></li>
              <% end %>
              <li><%=link_to "Log out", destroy_member_session_path, method: "delete"%></li>
          <% end %>


        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Global ILD Project</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <title><%= full_title(yield(:title)) %></title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/maps/modules/map.js"></script>
  <script src="https://code.highcharts.com/maps/modules/data.js"></script>
  <script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/mapdata/custom/world.js"></script>
  <!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
  <link rel="stylesheet" type="text/css" href="https://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css" />
  <%= csrf_meta_tags %>
</head>

    <body>

    <div class = "Application">

      <%= render 'layouts/header' %>

      <div class = "container">

        <div class = "row">

          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 Content">

            <%= yield %>

          </div>

        </div>

      </div>

      <div class = "container">

        <div class = "row">

          <div class="col-md-12 col-sm-12 col-xs-12">

            <%= render 'layouts/footer' %>

          </div>

        </div>

      </div>

    </div>

    </body>

</html>